### ISSUE TITLE
Explore the use of `PredefinedSplit` in scikit-learn for specifying custom folds

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#242]
scikit-learn v0.16 introduces [PredefinedSplit](http://scikit-learn.org/stable/modules/generated/sklearn.cross_validation.PredefinedSplit.html). Perhaps we can use that for our implementation of `cv_folds_file`?

**Comment by dan-blanchard** [comment]
I definitely like switching to that.

**Comment by aoifecahill** [comment]
I'm not sure this is going to be so straightforward. ``PredefinedSplit`` uses a fixed order list to record which testset each sample belongs to. Since we don't enforce that the order of ids in the cv folds be the same as in the data file, we would have to do additional book keeping to keep track of the links. And that's basically what we are doing already...

**Comment by desilinguist** [comment]
I am going to close this for now since it doesn't seem like this is going to buy us anything over what we are already doing.
