### ISSUE TITLE
Remove copy of DictVectorizer now that scikit-learn 0.16 has it

### ISSUE THREAD

**Issue by dan-blanchard** [EducationalTestingService/skll#263]
The latest releases of scikit-learn have the DictVectorizer we currently have in [`skll.data.dict_vectorizer`](https://github.com/EducationalTestingService/skll/blob/f98712ea850b52e47b8a94bef4a94023b39c6a1f/skll/data/dict_vectorizer.py).  We should delete that module and make it so that anywhere we create a `DictVectorizer` we are instantiating it with `sort=False` (which makes it use the much more memory efficient version that will not create copies of iterators passed to it).

**Comment by desilinguist** [comment]
I just tried to do this in [this branch](https://github.com/EducationalTestingService/skll/compare/feature/remove-our-dict-vectorizer?expand=1) but I get a lot of test failures. Some of them are due to floating point precision but a lot of them seem to be about `FeatureSet` equality. And this makes sense because the new `DictVectorizer` does *not* have an `__eq__()` method like ours does. So, I don't think this is going to be very straightforward. @dan-blanchard ?

**Comment by dan-blanchard** [comment]
Well, that's annoying.  I didn't realize they didn't take that as part of my PR (or maybe I just forgot to include it).  Since that's the only functional difference between the two, we should just have ours inherit directly from theirs and just have it add `__eq__`.  At least that way we'll get other bugfixes and such.

**Comment by desilinguist** [comment]
I tried this and I still get failures. I don't think this can be in 1.2 since it requires further investigation.

**Comment by desilinguist** [comment]
Addressed by #374.
