### ISSUE TITLE
smp does not exist

### ISSUE THREAD

**Issue by MagicYoung** [EducationalTestingService/skll#269]
Hi there,

When I am using run_experiment *.cfg, it raises the following errors:

drmaa.errors.DeniedByDrmException: code 17: job rejected: the requested parallel environment "smp" does not exist

I tried to check with:

$ qconf -sp smp
smp is not a parallel environment
$ qconf -spl
make
mpi
mpich
orte

Is there some suggestions on fixing it? Thanks.

Best

Xuesong

**Comment by dan-blanchard** [comment]
You'll need to enable `smp` for your GridEngine setup.  See the instructions [here](https://wiki.chipp.ch/twiki/bin/view/CmsTier3/SunGridEngine#Configure_a_parallel_environment).  I'm going to close this, because this is more of a [GridMap](https://github.com/pygridtools/gridmap) issue than a SKLL one.
