### ISSUE TITLE
Make sure examples and tutorial work before 2.0 release

### ISSUE THREAD

**Issue by aoifecahill** [EducationalTestingService/skll#529]
Currently the titanic example doesn't work (related to the fix for the readers). 

But we should also make sure that all other examples and the tutorial still work before the final release.

**Comment by aoifecahill** [comment]
We should also add this step to the release documentation (so that we don't have to keep filing these issues for every release).

**Comment by desilinguist** [comment]
Specifically, the titanic example won't work because `make_titanic_data.py` now behaves differently. In the old version -- before `pandas` was used as the backend for `CSVWriter` -- blank values were incorrectly backfilled to be 0s (see [this line](https://github.com/EducationalTestingService/skll/blob/v1.5.3/skll/data/writers.py#L319)). However, with `pandas`, the correct behavior happens, and blank values remain blank. 

So, we basically need to use the `pandas_kwargs` keyword argument in the new `CSVReader` class and filter out those rows which have any empty values. Does that make sense @jbiggsets?

**Comment by desilinguist** [comment]
Hmm, actually it looks like there's no keyword argument to pandas' `read_csv` that will filter out rows with NaNs _while_ reading. So, we can just use `FeatureSet.filter()` instead.

**Comment by jbiggsets** [comment]
Test the following:

## titanic
- [ ] `cross_validate.cfg`
- [ ] `evaluate_tuned.cfg`
- [ ] `evaluate.cfg`
- [ ] `learning_curve.cfg`
- [ ] `predict_train_only_tuned.cfg`
- [ ] `predict_train_only.cfg`
- [ ] `predict_train+dev_tuned.cfg`
- [ ] `predict_train+dev.cfg`
- [ ] `train.cfg`

## boston
- [ ] `cross_vali.cfg`
- [ ] `evaluate.cfg`

## iris
- [ ] `cross_vali.cfg`
- [ ] `evaluate.cfg`

**Comment by desilinguist** [comment]
@jbiggsets see also #544

**Comment by mulhod** [comment]
@jbiggsets Can you add the same comment over there, actually?

**Comment by desilinguist** [comment]
Addressed by #546.
